var1 = input('escreva algo:')
print('o tipo primitivo desse valor é', type(var1))
print('só tem espaços? ', var1.isspace())
print('é um número? ', var1.isnumeric())
print('é alfabético? ', var1.isalpha())
print('é alfanumérico? ', var1.isalnum())
print('está em seus superiores? ', var1.isupper())
print('esta é minúscula? ', var1.islower())
print('está maiúscula? ', var1.istitle())
